conf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('template_app/', include('template_app.urls')),
    path('form_example/', include('form_example.urls')),
    path('class_view/', include('class_view.urls')),
    path('logging_app/', include('logging_app.urls')),
    path('books/', include('books.urls')),


]

form_example/urls.py
from django.urls import path
from . import views

app_name = 'form_example'
urlpatterns = [
    path('', views.index, name='index'),
    path('your-name/', views.your_name, name='your_name'),
    path('thanks/', views.thanks, name='thanks'),
    path('contact/', views.contact_form, name='contact_form'),

]

form_example/models.py
# from django.db import models
from django import forms


class NameForm(forms.Form):
    # max_length 용도
    # 1> html input 엘리먼트에 maxlength="100" 효과
    # 2> form data validation check
    your_name = forms.CharField(label='Your Name', max_length=10) # default widget=Forms.TextInput
    # CharFiled default 위젯은 TextInput 클래스이며  이 위젯은 <input type='text'> tag 와 대응 된다.
    # 다른 위젯으로 변경하려면... your_name = forms.CharField(label='your name', max_length=100, widget=Forms.TextArea)


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField(label='email')
    cc_myself = forms.BooleanField(required=False)

form_example/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import NameForm
from .models import ContactForm

def index(request):
    return render(request, 'form_example/index.html')


def your_name(request):
    if request.method == 'GET':
        # 빈 폼을 사용자에게 보여 준다.
        # unbound form 생성
        nameForm = NameForm()

    elif request.method == 'POST':
        # 클라이언트 submit 요청 처리
        # bound form 생성하기
        nameForm = NameForm(request.POST)
        # validation check
        # 폼 검증 결과가 False 이면 맨 아래의 render 가 실행되며 이전 입력한 폼데이터가 전달된다.
        if nameForm.is_valid():
            # form data 가 유효하면, 데이터는 cleaned_data 로 복사된다.
            new_your_name = nameForm.cleaned_data['your_name']
            print('new_your_name: ', new_your_name)
            # 추가 로직이 있으면 실행함...

            # form post 요청은 항상 redirect!
            return HttpResponseRedirect('thanks/')

    return render(request, 'form_example/name.html', {'nameForm': nameForm})


def thanks(request):
    return render(request, 'form_example/thanks.html')


def contact_form(request):
    global contact_form
    if request.method == 'GET':
        contact_form = ContactForm()

    elif request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            subject = contact_form.cleaned_data['subject']
            message = contact_form.cleaned_data['message']
            sender = contact_form.cleaned_data['sender']
            cc_myself = contact_form.cleaned_data['cc_myself']
            print('subject:', subject, ', message:', message, 'sender:', sender, ',cc_myself:', cc_myself)
            return HttpResponseRedirect(reverse('form_example:thanks'))

    return render(request, 'form_example/contact.html', {'contact_form': contact_form})

form_example/templates/form_example/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>contact</title>
</head>
<body>
<form action="{% url 'form_example:contact_form' %}" method="post">
    {% csrf_token %}
    <h3>Contact </h3>
    {{ contact_form.as_p }}
    <input type="submit" value="Submit">
</form>
</body>
</html>

form_example/templates/form_example/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>form-index</title>
</head>
<body>
    <h1>form_example</h1>
    <ul>
        <li><a href="{% url 'form_example:your_name' %}">1. your-name page</a></li>
        <li><a href="{% url 'form_example:contact_form' %}">2. contact-form page</a></li>
    </ul>


</body>
</html>

form_example/templates/form_example/name.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>name</title>
</head>
<body>
{#    <form action="/your-name/" method="post">#}
{#        <label for="your_name">Your name: </label>#}
{#        <input type="text" id="your_name" name="your_name" value="{{ current_name }} ">#}
{#        <input type="submit" value="Send" />#}
{#    </form>#}

    <form action="{% url 'form_example:your_name' %}" method="post">
        {% csrf_token %}
        {{ nameForm }}

        <!-- <p> tag 로 둘러 싼다. -->
{#        {{ nameForm.as_p }}#}

        <!-- <li> tag 로 만들어 주며 ul, ol은 개발자가 만들어 줘야 한다. -->
{#        <ul>#}
{#            {{ nameForm.as_ul }}#}
{#        </ul>#}

        <!-- <th>, <tr> tag 로 둘러 싸 주며 <table> tag 는 직접 만들어야 한다. -->
{#        <table>#}
{#            <tbody>#}
{#                {{ nameForm.as_table }}#}
{#            </tbody>#}
{#        </table>#}

        <input type="submit" value="Submit" />
    </form>

</body>
</html>

form_example/templates/form_example/thanks.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thanks</title>
</head>
<body>
    <h1>Thanks</h1>
</body>
</html>