conf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('template_app/', include('template_app.urls')),
    path('form_example/', include('form_example.urls')),
    path('class_view/', include('class_view.urls')),
    path('logging_app/', include('logging_app.urls')),
    path('books/', include('books.urls')),


]

template_app/urls.py
from . import views
from django.urls import path

app_name = 'template_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),
    path('main/', views.main, name='main'),
]

template_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'template_app/index.html')

def base(request):
    return render(request, 'template_app/base.html')


def main(request):
    context = {
        "hobbies": ["music", "walking", 'games', 'dance']
    }
    return render(request, 'template_app/main.html', context)

template_app/templates/template_app/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
    <meta charset="UTF-8">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol-debug.css" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol-debug.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/openlayers/4.6.5/ol.js"></script>
        {% block title %}
            <title>Base.html</title>
        {% endblock %}
    </head>
<body>

{% block h %}
    <h1>this is base title</h1>
{% endblock %}


<div id="sidebar">
    <h3>side-bar</h3>
    {% block sidebar %}
        <ul>
            <li><a href="/">Home</a></li>
            <li><a href="/blog/">blog</a></li>
            <li><a href="/profile/">profile</a></li>
        </ul>
    {% endblock %}
</div>

<div id="content">
    {% block content %}
        <h2>this is base.html</h2>
        <p> base.html is base and parent template.</p>
        <p>that has many things. title, sidebar, and content</p>
    {% endblock %}
</div>


</body>
</html>

template_app/templates/template_app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
    <h1>template extends</h1>
    <ul>
        <li><a href="{% url 'template_app:base' %}">template-extend-study : base </a></li>
        <li><a href="{% url 'template_app:main' %}">template-extend-study : main </a></li>
    </ul>
</body>
</html>

template_app/templates/template_app/main.html
{% extends 'template_app/base.html' %}

{% comment '' %}
this is coomment rows

{% endcomment %}

{% block title %}
    <title>main.html</title>
{% endblock title %}

{% block h %}
    <h1> this is main title</h1>
{% endblock h %}


{% block content %}
    <p>main.html content is ... </p>
    <ul>
        {% for hobby in hobbies %}
            <li> {{ hobby }}</li>
    {% endfor %}
    </ul>
{% endblock content %}