class_view/urls.py
from django.urls import path
# 함수 형 뷰 사용
from . import views

# Class 형 뷰 사용
from .views import MyClassView
from .views import AboutView
from .views import MyFormGenericView
from django.views.generic import TemplateView


app_name = 'class_view'
urlpatterns = [
    path('', views.index, name='index'),

    # 장고의 URL 해석기는 요청과 관련된 파라미터들을 클래스가 아니라 함수에 전달 하기 때문에,
    # 클래스형 뷰는 클래스로 진입하기 위한 as_view() 클래스 메소드를 제공한다.
    # as_view() 를 진입 메소드 라고도 한다. 이 메소드의 역할은 클래스의 인스턴스를 생성하고
    # 그 인스턴스의 dispatch() 메서드를 호출한다.
    # dispatch() 메서드는 요청을 검사해서 GET, POST 등의 HTTP Method 를 알아낸 다음
    # 인스턴스 내에서 해당 이름을 갖는 메서드로 요청을 중계 해준다.
    # 만약 해당 메서드가 없으면 HttpResponseNotAllow 예외를 발생시킴
    path('first-class-view/', MyClassView.as_view()),

    # 템플릿 뷰 를 상속 재정의 하였음
    path('about1/', AboutView.as_view()),
    # 이방식은 템플릿 뷰를 상속하여 AboutView 만들지 않고 템플릿 뷰를 직접 변경하여 이용함 (아래위 결과는 같음)
    path('about2/', TemplateView.as_view(template_name="class_view/about.html")),
    path('success/', TemplateView.as_view(template_name="class_view/success.html")),

    # function view - get, post 처리
    path('my-function-view/', views.my_function_view, name='my_function_view'),
    path('my-form-generic-view/', MyFormGenericView.as_view(), name='my-form-generic-view')
]

conf/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('polls/', include('polls.urls')),
    path('template_app/', include('template_app.urls')),
    path('form_example/', include('form_example.urls')),
    path('class_view/', include('class_view.urls')),
    path('logging_app/', include('logging_app.urls')),
    path('books/', include('books.urls')),


]

form_example/urls.py
from django.urls import path
from . import views

app_name = 'form_example'
urlpatterns = [
    path('', views.index, name='index'),
    path('your-name/', views.your_name, name='your_name'),
    path('thanks/', views.thanks, name='thanks'),
    path('contact/', views.contact_form, name='contact_form'),

]

logging_app/urls.py
from django.urls import path
from . import views

app_name = 'logging_app'
urlpatterns = [
    path('', views.index, name='index'),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

template_app/urls.py
from . import views
from django.urls import path

app_name = 'template_app'
urlpatterns = [
    path('', views.index, name='index'),
    path('base/', views.base, name='base'),
    path('main/', views.main, name='main'),
]

polls/models.py
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, 'Question FK')

    def __str__(self):
        return self.choice_text

polls/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import reverse
from django.http import HttpResponseRedirect
from .models import Question
from .models import Choice


def index(request):
    latest_question_list = Question.objects.all().order_by('-pub_date')[0:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context=context)


def detail(request, question_id):
    # context = {
      #  'question': Question.objects.filter(pk=request.GET['question_id']),
       # 'error_message': error_message
    # }
    # return render(request, 'polls/detail.html', context=context)

    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        choice_id = request.POST['choice']
        selected_choice = question.choice_set.get(pk=choice_id)
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            "question": question,
            "error_message": "you didn't select a choice"
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question_id, )))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>

<h1>{{ question.question_text }}</h1>

{% if error_message %}
    <p><strong> {{ error_message }}</strong></p>
{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="POST">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}"> {{ choice.choice_text }}</label>
        <br>
    {% endfor %}
    <input type="submit" value="vote">
</form>

</body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Index</title>
</head>
<body>
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}"> {{ question.question_text }}</a></li>
    {% endfor %}
        <li><a href="{% url 'template_app:index' %}">template-extend : index</a></li>
        <li><a href="{% url 'form_example:index' %}">form_example : index </a></li>
        <li><a href="{% url 'class_view:index' %}">class view example : index</a></li>
        <li><a href="{% url 'logging_app:index' %}">logging_app : index</a></li>


    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Results</title>
</head>
<body>
    <h2> {{ quesiton.question_text }}</h2>
    <ul>
        {% for choice in question.choice_set.all %}
            <li> {{ choice.choice_text }} - {{ choice.votes }} vote{{  choice.votes | pluralize }}</li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote Again?</a>

</body>
</html>